language: c

matrix:
  include:
    - os: linux
      env: COMPILER=4.02.3 LIBEV=no
    - os: linux
      env: COMPILER=4.03.0
    - os: linux
      env: COMPILER=4.04.2
    - os: linux
      env: COMPILER=4.05.0
    - os: linux
      env: COMPILER=4.06.1
    - os: linux
      env: COMPILER=4.07.1
    - os: linux
      env: COMPILER=ocaml-variants.4.07.1+flambda
    - os: linux
      env: COMPILER=ocaml-variants.4.08.0+beta2 REPOSITORIES=--repositories=default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git
    - os: osx
      env: COMPILER=4.07.1
    - os: osx
      env: COMPILER=4.07.1 LIBEV=no

  fast_finish: true

  allow_failures:
    - env: COMPILER=ocaml-variants.4.08.0+beta2 REPOSITORIES=--repositories=default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git

env:
  global:
    - LWT_FORCE_LIBEV_BY_DEFAULT=yes
    - LWT_STRESS_TEST=true

script: bash -e src/util/travis.sh

cache:
  directories:
    - $HOME/.opam

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
