name: Ctypes

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ocaml-compiler: 4.03.0
          - os: ubuntu-latest
            ocaml-compiler: 4.04.0
          - os: ubuntu-latest
            ocaml-compiler: 4.05.0
          - os: ubuntu-latest
            ocaml-compiler: 4.06.0
          - os: ubuntu-latest
            ocaml-compiler: 4.07.0
          - os: ubuntu-latest
            ocaml-compiler: 4.08.0
          - os: ubuntu-latest
            ocaml-compiler: 4.09.0
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.11.2+fp+flambda
          - os: ubuntu-latest
            ocaml-compiler: 4.11.1
          - os: ubuntu-latest
            ocaml-compiler: 4.12.0
          - os: ubuntu-latest
            ocaml-compiler: 4.13.1
          - os: ubuntu-latest
            ocaml-compiler: 4.14.0
          - os: windows-latest
            ocaml-compiler: 4.13.1
          - os: macos-latest
            ocaml-compiler: 4.13.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Deps
        run: |
          opam pin add -n ctypes.dev .
          opam pin add -n ctypes-foreign.dev .
          opam depext -ty ctypes ctypes-foreign
          opam install -t --deps-only .

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest
