language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="tyxml:. tyxml-ppx:. tyxml-jsx:. tyxml-syntax:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="tyxml" OCAML_VERSION="4.02.3"
  - PACKAGE="tyxml" OCAML_VERSION="4.03.0"
  - PACKAGE="tyxml" OCAML_VERSION="4.04.2"
  - PACKAGE="tyxml" OCAML_VERSION="4.05.0"
  - PACKAGE="tyxml" OCAML_VERSION="4.06.1"
  - PACKAGE="tyxml" OCAML_VERSION="4.07.1"
  - PACKAGE="tyxml" OCAML_VERSION="4.08.1"
  - PACKAGE="tyxml" OCAML_VERSION="4.09.0"
  - PACKAGE="tyxml-ppx" OCAML_VERSION="4.02.3"
  - PACKAGE="tyxml-ppx" OCAML_VERSION="4.04.2"
  - PACKAGE="tyxml-ppx" OCAML_VERSION="4.06.1"
  - PACKAGE="tyxml-ppx" OCAML_VERSION="4.08.1"
  - PACKAGE="tyxml-ppx" OCAML_VERSION="4.09.0"
  - PACKAGE="tyxml-jsx" OCAML_VERSION="4.02.3"
  - PACKAGE="tyxml-jsx" OCAML_VERSION="4.04.2"
  - PACKAGE="tyxml-jsx" OCAML_VERSION="4.06.1"
  - PACKAGE="tyxml-jsx" OCAML_VERSION="4.08.1"
  - PACKAGE="tyxml-jsx" OCAML_VERSION="4.09.0"
  allow_failures:
  - PACKAGE="tyxml tyxml-ppx tyxml-jsx" OCAML_VERSION="4.08.1" REVDEPS="*"
