language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="ipaddr"
   - PINS="ipaddr:. macaddr:. ipaddr-sexp:. macaddr-sexp:. ipaddr-cstruct:. macaddr-cstruct:."
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.04
   - DISTRO=ubuntu OCAML_VERSION=4.05
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=fedora OCAML_VERSION=4.07
   - DISTRO=alpine OCAML_VERSION=4.08
   - DISTRO=alpine OCAML_VERSION=4.09
   - DISTRO=alpine OCAML_VERSION=4.10
